---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lego-bridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: lego-bridge
    service: lego-bridge
    component: lego-bridge
    id: lego-bridge
stringData:
  PDNS_API_URL: "http://ns1-api.apps.k8s.kemo.labs/"
  PDNS_API_KEY: supersecretapikey
  ACME_SERVER_URL: "https://step-ca.apps.k8s.kemo.labs/acme/acme/directory"
  EMAIL_ADDRESS: "ken@kenmoini.com"
  DNS_SERVERS: "192.168.42.9,192.168.42.10"
  DNS_SERVER_ONE: "192.168.42.9"
  DNS_SERVER_TWO: "192.168.42.10"
